### Numpy

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
marks=[65,76,83,70,50]
marks_array=np.array(marks)
print(marks_array)
print(arr)

[65 76 83 70 50]
[1 2 3 4 5]


#### Dimensions

In [4]:
print(arr.ndim)
arr2=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr2.ndim)

1
2


#### Number of rows and columns

In [6]:
print(arr.shape)

(5,)


In [7]:
print(arr2.shape)

(3, 3)


#### Number of Elements

In [8]:
print(arr2.size)
print(arr.size)

9
5


#### Array Operations

In [11]:
a=np.array([10,20,30])
b=np.array([1,2,3])
print(a+b)

[11 22 33]


In [15]:
arr3=np.array([1])
print(a+arr3)

[11 21 31]


In [16]:
a=np.array([10,20,30])
b=np.array([1,2,3])
print(a-b)

[ 9 18 27]


In [17]:
a=np.array([10,20,30])
b=np.array([1,2,3])
print(a*b)

[10 40 90]


In [18]:
a=np.array([10,20,30])
b=np.array([1,2,3])
print(a/b)

[10. 10. 10.]


In [19]:
a=np.array([10,20,30])
b=np.array([1,2,3])
print(a//b)

[10 10 10]


In [20]:
a=np.array([10,20,30])
b=np.array([1,2,3])
print(a%b)

[0 0 0]


In [21]:
print(arr.dtype)

int64


#### Mathematical Operations

In [22]:
c=np.array([10,245,6,8,9,0])
print(np.sqrt(c))

[ 3.16227766 15.65247584  2.44948974  2.82842712  3.          0.        ]


In [23]:
print(np.pow(c,2))

[  100 60025    36    64    81     0]


#### Scalar operation

In [24]:
a=np.array([10,20,30])
b=np.array([1,2,3])
print(a+b)
print(a+5)
print(a-1)
print(b*3)

[11 22 33]
[15 25 35]
[ 9 19 29]
[3 6 9]


#### Array operations with Aggregate Functions

In [25]:
arr=np.array([10,20,30,40,50])
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.sum(arr))

10
50
30.0
150
